// =========================================================
// إعدادات جميع الخدمات - ملف مركزي
// =========================================================

export const SERVICES_CONFIG = {
  'initial-review': {
    id: 'initial-review',
    slug: 'initial-review',
    icon_name: 'CheckCircle',
    title_ar: 'التحكيم الأولي',
    title_en: 'Initial Review',
    desc_ar: 'خدمة التحكيم الأولي للأبحاث والأوراق العلمية قبل النشر في المجلات',
    desc_en: 'Initial peer review service for research papers before journal publication',
    long_desc_ar: 'نقدم لك تحكيماً أولياً شاملاً من محكمين أكاديميين معتمدين لتقييم جودة بحثك من حيث المنهجية، الأصالة، والالتزام بمعايير النشر العلمي قبل إرساله للمجلة المستهدفة.',
    long_desc_en: 'We provide a comprehensive initial review by certified academic reviewers to assess your research quality in terms of methodology, originality, and compliance with scientific publication standards before submitting to your target journal.',
    color_class: 'from-emerald-500 to-emerald-700',
    color_bg: 'bg-emerald-50',
    color_text: 'text-emerald-600',
    color_border: 'border-emerald-200',
    roles: ['undergrad', 'grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'تقييم شامل لجودة البحث ومنهجيته',
      'فحص الأصالة والابتكار العلمي',
      'مراجعة الهيكل التنظيمي للورقة',
      'تقديم تقرير تفصيلي بالملاحظات والتوصيات',
      'تحديد نقاط الضعف والقوة في البحث',
      'تقدير مدى جاهزية البحث للنشر',
    ],
    features_en: [
      'Comprehensive assessment of research quality and methodology',
      'Originality and scientific innovation check',
      'Review of the paper organizational structure',
      'Detailed report with notes and recommendations',
      'Identification of research strengths and weaknesses',
      'Estimation of publication readiness',
    ],
    steps_ar: [
      { title: 'رفع البحث', desc: 'ارفع ملف البحث بصيغة PDF أو Word' },
      { title: 'تعيين محكم', desc: 'نختار محكماً متخصصاً في مجالك' },
      { title: 'التحكيم', desc: 'يتم مراجعة البحث خلال 3-5 أيام عمل' },
      { title: 'استلام التقرير', desc: 'تحصل على تقرير تفصيلي بالملاحظات' },
    ],
    steps_en: [
      { title: 'Upload Research', desc: 'Upload your research file in PDF or Word format' },
      { title: 'Assign Reviewer', desc: 'We select a specialized reviewer in your field' },
      { title: 'Review Process', desc: 'Research is reviewed within 3-5 business days' },
      { title: 'Receive Report', desc: 'You receive a detailed report with comments' },
    ],
    upload_label_ar: 'رفع ملف البحث',
    upload_label_en: 'Upload Research File',
    upload_accept: '.pdf,.doc,.docx',
    cta_text_ar: 'طلب التحكيم الأولي',
    cta_text_en: 'Request Initial Review',
  },

  'translation': {
    id: 'translation',
    slug: 'translation',
    icon_name: 'ExternalLink',
    title_ar: 'الترجمة',
    title_en: 'Translation',
    desc_ar: 'ترجمة الأوراق البحثية والمستندات الأكاديمية باحترافية عالية',
    desc_en: 'Professional translation of research papers and academic documents',
    long_desc_ar: 'فريق من المترجمين المتخصصين في الترجمة الأكاديمية يضمن لك دقة المصطلحات العلمية والتعبيرات الأكاديمية المعتمدة، مع الحفاظ على المعنى العلمي الأصيل.',
    long_desc_en: 'A team of specialized academic translators ensures accurate scientific terminology and standard academic expressions while preserving the original scientific meaning.',
    color_class: 'from-blue-500 to-blue-700',
    color_bg: 'bg-blue-50',
    color_text: 'text-blue-600',
    color_border: 'border-blue-200',
    roles: ['undergrad', 'grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'مترجمون متخصصون في المجال الأكاديمي',
      'دقة في المصطلحات العلمية والتقنية',
      'ترجمة عربية-إنجليزية وإنجليزية-عربية',
      'مراجعة لغوية بعد الترجمة',
      'الحفاظ على التنسيق الأصلي للورقة',
      'تعديلات مجانية عند الحاجة',
    ],
    features_en: [
      'Translators specialized in the academic field',
      'Accuracy in scientific and technical terminology',
      'Arabic-English and English-Arabic translation',
      'Language editing after translation',
      'Preservation of original paper formatting',
      'Free revisions when needed',
    ],
    steps_ar: [
      { title: 'رفع الملف', desc: 'ارفع الورقة أو المستند المطلوب ترجمته' },
      { title: 'تحديد التفاصيل', desc: 'حدد اللغة المطلوبة والمجال العلمي' },
      { title: 'الترجمة', desc: 'يتم الترجمة من قبل متخصص معتمد' },
      { title: 'التسليم', desc: 'استلم الترجمة بتنسيقها الأصلي' },
    ],
    steps_en: [
      { title: 'Upload File', desc: 'Upload the paper or document to be translated' },
      { title: 'Specify Details', desc: 'Specify target language and scientific field' },
      { title: 'Translation', desc: 'Translation by a certified specialist' },
      { title: 'Delivery', desc: 'Receive translation in original format' },
    ],
    upload_label_ar: 'رفع الملف للترجمة',
    upload_label_en: 'Upload File for Translation',
    upload_accept: '.pdf,.doc,.docx,.tex',
    cta_text_ar: 'طلب الترجمة',
    cta_text_en: 'Request Translation',
  },

  'proofreading': {
    id: 'proofreading',
    slug: 'proofreading',
    icon_name: 'FileText',
    title_ar: 'التدقيق اللغوي',
    title_en: 'Language Editing',
    desc_ar: 'تدقيق لغوي شامل للأوراق البحثية وفقاً للمعايير الأكاديمية الدولية',
    desc_en: 'Comprehensive language editing for research papers per international academic standards',
    long_desc_ar: 'تدقيق لغوي احترافي يضمن خلو ورقتك من الأخطاء النحوية والإملائية والأسلوبية، مع تحسين الوضوح والانسيابية وفقاً لمعايير النشر في المجلات العلمية المحكّمة.',
    long_desc_en: 'Professional language editing ensuring your paper is free of grammatical, spelling, and stylistic errors, while improving clarity and fluency according to peer-reviewed journal publication standards.',
    color_class: 'from-violet-500 to-violet-700',
    color_bg: 'bg-violet-50',
    color_text: 'text-violet-600',
    color_border: 'border-violet-200',
    roles: ['undergrad', 'grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'تصحيح الأخطاء النحوية والإملائية',
      'تحسين الأسلوب الأكاديمي والانسيابية',
      'توحيد المصطلحات عبر الورقة',
      'الالتزام بأسلوب APA/Harvard/IEEE',
      'تتبع التعديلات (Track Changes)',
      'تقرير مفصل بالتعديلات المُدخلة',
    ],
    features_en: [
      'Correction of grammatical and spelling errors',
      'Improvement of academic style and fluency',
      'Terminology consistency across the paper',
      'Compliance with APA/Harvard/IEEE style',
      'Track Changes for all modifications',
      'Detailed report of changes made',
    ],
    steps_ar: [
      { title: 'رفع الورقة', desc: 'ارفع ملف البحث بصيغة Word' },
      { title: 'تحديد النمط', desc: 'اختر أسلوب التوثيق المطلوب' },
      { title: 'التدقيق', desc: 'يقوم متخصص بالتدقيق اللغوي الشامل' },
      { title: 'استلام النتيجة', desc: 'تحصل على الملف مع تتبع التعديلات' },
    ],
    steps_en: [
      { title: 'Upload Paper', desc: 'Upload your research file in Word format' },
      { title: 'Select Style', desc: 'Choose the required citation style' },
      { title: 'Editing', desc: 'Specialist performs comprehensive language editing' },
      { title: 'Receive Result', desc: 'Get the file with tracked changes' },
    ],
    upload_label_ar: 'رفع الورقة للتدقيق',
    upload_label_en: 'Upload Paper for Editing',
    upload_accept: '.doc,.docx',
    cta_text_ar: 'طلب التدقيق اللغوي',
    cta_text_en: 'Request Language Editing',
  },

  'consultation': {
    id: 'consultation',
    slug: 'consultation',
    icon_name: 'HandCoins',
    title_ar: 'الاستشارة',
    title_en: 'Consultation',
    desc_ar: 'استشارات أكاديمية وبحثية متخصصة مع خبراء معتمدين',
    desc_en: 'Specialized academic and research consultations with certified experts',
    long_desc_ar: 'احصل على استشارة مباشرة مع خبير أكاديمي متخصص لمساعدتك في تحديد مسار بحثك، اختيار المنهجية المناسبة، أو حل أي إشكالية علمية تواجهك.',
    long_desc_en: 'Get direct consultation with a specialized academic expert to help you define your research path, choose the right methodology, or resolve any scientific challenge you face.',
    color_class: 'from-amber-500 to-amber-700',
    color_bg: 'bg-amber-50',
    color_text: 'text-amber-600',
    color_border: 'border-amber-200',
    roles: ['undergrad', 'grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'استشارة مباشرة مع خبير متخصص',
      'مساعدة في اختيار موضوع البحث',
      'توجيه منهجي شامل',
      'مراجعة خطة البحث',
      'نصائح حول النشر الأكاديمي',
      'متابعة بعد الاستشارة',
    ],
    features_en: [
      'Direct consultation with a specialized expert',
      'Help with research topic selection',
      'Comprehensive methodological guidance',
      'Research plan review',
      'Academic publishing advice',
      'Follow-up after consultation',
    ],
    steps_ar: [
      { title: 'طلب الاستشارة', desc: 'حدد مجال الاستشارة والمشكلة' },
      { title: 'اختر موعداً', desc: 'اختر الوقت المناسب لك' },
      { title: 'جلسة الاستشارة', desc: 'اجلس مع الخبير مباشرة' },
      { title: 'التوصيات', desc: 'استلم ملخص التوصيات والخطوات' },
    ],
    steps_en: [
      { title: 'Request Consultation', desc: 'Specify consultation area and problem' },
      { title: 'Choose Time', desc: 'Select a convenient time for you' },
      { title: 'Consultation Session', desc: 'Meet directly with the expert' },
      { title: 'Recommendations', desc: 'Receive summary of recommendations and steps' },
    ],
    upload_label_ar: 'رفع مستندات إضافية (اختياري)',
    upload_label_en: 'Upload additional documents (optional)',
    upload_accept: '.pdf,.doc,.docx,.pptx',
    cta_text_ar: 'طلب استشارة',
    cta_text_en: 'Request Consultation',
  },

  'ai-assistant': {
    id: 'ai-assistant',
    slug: 'ai-assistant',
    icon_name: 'TrendingUp',
    title_ar: 'المساعد الذكي',
    title_en: 'AI Assistant',
    desc_ar: 'مساعد ذكي مدعوم بالذكاء الاصطناعي لتحسين الأبحاث والكتابة الأكاديمية',
    desc_en: 'AI-powered assistant to enhance research and academic writing',
    long_desc_ar: 'أداة ذكاء اصطناعي متطورة مصممة خصيصاً للباحثين الأكاديميين، تساعدك في صياغة الجمل، تحسين الأسلوب، اقتراح مراجع، وتلخيص الأبحاث بضغطة زر.',
    long_desc_en: 'An advanced AI tool designed specifically for academic researchers, helping you with sentence formulation, style improvement, reference suggestions, and research summarization at the click of a button.',
    color_class: 'from-cyan-500 to-cyan-700',
    color_bg: 'bg-cyan-50',
    color_text: 'text-cyan-600',
    color_border: 'border-cyan-200',
    roles: ['undergrad', 'grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'تحسين صياغة النصوص الأكاديمية',
      'اقتراح مراجع علمية ذات صلة',
      'تلخيص الأبحاث الطويلة',
      'فحص التشابه النصي المبدئي',
      'ترجمة فورية للمصطلحات',
      'متاح على مدار الساعة',
    ],
    features_en: [
      'Improvement of academic text formulation',
      'Suggestion of relevant scientific references',
      'Summarization of long research papers',
      'Initial text similarity check',
      'Instant terminology translation',
      'Available 24/7',
    ],
    steps_ar: [
      { title: 'الدخول للمساعد', desc: 'انتقل إلى واجهة المساعد الذكي' },
      { title: 'إدخال النص', desc: 'الصق النص أو ارفع الملف' },
      { title: 'اختيار الخدمة', desc: 'حدد نوع المساعدة المطلوبة' },
      { title: 'النتيجة', desc: 'احصل على النتيجة فوراً' },
    ],
    steps_en: [
      { title: 'Access Assistant', desc: 'Navigate to the AI assistant interface' },
      { title: 'Input Text', desc: 'Paste text or upload file' },
      { title: 'Select Service', desc: 'Specify the type of assistance needed' },
      { title: 'Result', desc: 'Get results instantly' },
    ],
    upload_label_ar: 'يرجى استخدام واجهة المساعد الذكي مباشرة',
    upload_label_en: 'Please use the AI Assistant interface directly',
    upload_accept: null,
    cta_text_ar: 'فتح المساعد الذكي',
    cta_text_en: 'Open AI Assistant',
  },

  // ---- خدمات الأدوار المتقدمة ----

  'expert-review': {
    id: 'expert-review',
    slug: 'expert-review',
    icon_name: 'Shield',
    title_ar: 'تحكيم خبير',
    title_en: 'Expert Review',
    desc_ar: 'تحكيم متعمق من خبير متخصص في مجال البحث لضمان الجودة العلمية',
    desc_en: 'In-depth review by a specialized expert in the research field to ensure scientific quality',
    long_desc_ar: 'تحكيم علمي متقدم يجريه خبير لديه خبرة بحثية ونشر في نفس تخصصك الدقيق، مع تقييم معمّق للمنهجية والنتائج والاستنتاجات وتقديم توصيات دقيقة للتحسين.',
    long_desc_en: 'Advanced scientific review conducted by an expert with research and publication experience in your exact specialty, with in-depth evaluation of methodology, results, conclusions, and precise improvement recommendations.',
    color_class: 'from-indigo-500 to-indigo-700',
    color_bg: 'bg-indigo-50',
    color_text: 'text-indigo-600',
    color_border: 'border-indigo-200',
    roles: ['grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'محكم خبير في التخصص الدقيق',
      'تقييم معمّق للمنهجية والإحصاء',
      'تحليل نقدي للنتائج والاستنتاجات',
      'مقارنة مع الأدبيات السابقة',
      'توصيات عملية قابلة للتطبيق',
      'ضمان سرية البحث الكاملة',
    ],
    features_en: [
      'Expert reviewer in the exact specialty',
      'In-depth evaluation of methodology and statistics',
      'Critical analysis of results and conclusions',
      'Comparison with previous literature',
      'Practical and actionable recommendations',
      'Complete research confidentiality guarantee',
    ],
    steps_ar: [
      { title: 'رفع البحث', desc: 'ارفع البحث مع تحديد التخصص الدقيق' },
      { title: 'اختيار الخبير', desc: 'نرشح خبيراً أو تختاره أنت' },
      { title: 'التحكيم المعمق', desc: 'مراجعة شاملة خلال 5-7 أيام عمل' },
      { title: 'تقرير الخبير', desc: 'تقرير تفصيلي مع توصيات محددة' },
    ],
    steps_en: [
      { title: 'Upload Research', desc: 'Upload research specifying exact specialty' },
      { title: 'Select Expert', desc: 'We recommend or you choose an expert' },
      { title: 'In-depth Review', desc: 'Comprehensive review within 5-7 business days' },
      { title: 'Expert Report', desc: 'Detailed report with specific recommendations' },
    ],
    upload_label_ar: 'رفع ملف البحث',
    upload_label_en: 'Upload Research File',
    upload_accept: '.pdf,.doc,.docx',
    cta_text_ar: 'طلب تحكيم خبير',
    cta_text_en: 'Request Expert Review',
  },

  'final-review': {
    id: 'final-review',
    slug: 'final-review',
    icon_name: 'Star',
    title_ar: 'التحكيم النهائي',
    title_en: 'Final Review',
    desc_ar: 'تحكيم نهائي شامل قبل الإرسال للمجلة لضمان جاهزية البحث للنشر',
    desc_en: 'Comprehensive final review before journal submission to ensure publication readiness',
    long_desc_ar: 'مراجعة نهائية شاملة تجمع بين التحكيم العلمي والتدقيق اللغوي وفحص التوافق مع متطلبات المجلة المستهدفة، لضمان تقديم بحثك بأفضل صورة ممكنة.',
    long_desc_en: 'A comprehensive final review combining scientific review, language editing, and compliance check with target journal requirements, ensuring your research is presented in the best possible form.',
    color_class: 'from-yellow-500 to-yellow-700',
    color_bg: 'bg-yellow-50',
    color_text: 'text-yellow-600',
    color_border: 'border-yellow-200',
    roles: ['grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'تحكيم علمي + تدقيق لغوي معاً',
      'فحص التوافق مع متطلبات المجلة',
      'مراجعة الهيكل والتنسيق',
      'فحص المراجع والدلالات',
      'تقييم شامل للجاهزية',
      'ضمان تقليل احتمالية الرفض',
    ],
    features_en: [
      'Scientific review + language editing combined',
      'Compliance check with journal requirements',
      'Structure and formatting review',
      'References and citations check',
      'Comprehensive readiness assessment',
      'Guaranteed reduction of rejection probability',
    ],
    steps_ar: [
      { title: 'رفع البحث والمجلة', desc: 'ارفع البحث وحدد المجلة المستهدفة' },
      { title: 'المراجعة الشاملة', desc: 'فريق متعدد التخصصات يراجع البحث' },
      { title: 'التعديلات', desc: 'ننفذ التعديلات المطلوبة أو نرشحها' },
      { title: 'التسليم النهائي', desc: 'بحث جاهز للإرسال للمجلة' },
    ],
    steps_en: [
      { title: 'Upload Research & Journal', desc: 'Upload research and specify target journal' },
      { title: 'Comprehensive Review', desc: 'Multidisciplinary team reviews the research' },
      { title: 'Modifications', desc: 'We implement or suggest required changes' },
      { title: 'Final Delivery', desc: 'Research ready for journal submission' },
    ],
    upload_label_ar: 'رفع ملف البحث',
    upload_label_en: 'Upload Research File',
    upload_accept: '.pdf,.doc,.docx',
    cta_text_ar: 'طلب التحكيم النهائي',
    cta_text_en: 'Request Final Review',
  },

  'journal-selection': {
    id: 'journal-selection',
    slug: 'journal-selection',
    icon_name: 'BookMarked',
    title_ar: 'اختيار مجلة',
    title_en: 'Journal Selection',
    desc_ar: 'مساعدة في اختيار المجلة العلمية الأنسب لنشر بحثك بناءً على معايير دقيقة',
    desc_en: 'Help selecting the most suitable scientific journal for your research based on precise criteria',
    long_desc_ar: 'نحلل بحثك تحليلاً عميقاً ونقارنه مع آلاف المجلات العلمية المحكّمة لنرشح لك أفضل 3-5 مجلات تناسب مجالك ومستوى بحثك وأهدافك النشرية.',
    long_desc_en: 'We deeply analyze your research and compare it with thousands of peer-reviewed journals to recommend the best 3-5 journals matching your field, research level, and publication goals.',
    color_class: 'from-pink-500 to-pink-700',
    color_bg: 'bg-pink-50',
    color_text: 'text-pink-600',
    color_border: 'border-pink-200',
    roles: ['grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'تحليل موضوع البحث والكلمات المفتاحية',
      'مطابقة مع قاعدة بيانات المجلات',
      'مراعاة معامل التأثير والتصنيف',
      'مراعاة سرعة النشر والتكلفة',
      'ترشيح 3-5 مجلات مرتبة',
      'تقرير مفصل بكل مجلة مرشحة',
    ],
    features_en: [
      'Analysis of research topic and keywords',
      'Matching with journal database',
      'Consideration of impact factor and ranking',
      'Consideration of publication speed and cost',
      'Recommendation of 3-5 ranked journals',
      'Detailed report for each recommended journal',
    ],
    steps_ar: [
      { title: 'رفع الملخص', desc: 'ارفع ملخص البحث أو البحث الكامل' },
      { title: 'تحديد التفضيلات', desc: 'حدد أولوياتك (سرعة، تكلفة، تصنيف)' },
      { title: 'التحليل', desc: 'نحلل ونطابق مع أفضل المجلات' },
      { title: 'التوصيات', desc: 'استلم قائمة المجلات المرشحة مع التقرير' },
    ],
    steps_en: [
      { title: 'Upload Abstract', desc: 'Upload abstract or full research' },
      { title: 'Set Preferences', desc: 'Specify priorities (speed, cost, ranking)' },
      { title: 'Analysis', desc: 'We analyze and match with best journals' },
      { title: 'Recommendations', desc: 'Receive recommended journals list with report' },
    ],
    upload_label_ar: 'رفع الملخص أو البحث',
    upload_label_en: 'Upload Abstract or Research',
    upload_accept: '.pdf,.doc,.docx',
    cta_text_ar: 'طلب اختيار مجلة',
    cta_text_en: 'Request Journal Selection',
  },

  'journal-evaluation': {
    id: 'journal-evaluation',
    slug: 'journal-evaluation',
    icon_name: 'BarChart3',
    title_ar: 'تقييم مجلة',
    title_en: 'Journal Evaluation',
    desc_ar: 'تقييم شامل للمجلات العلمية من حيث معامل التأثير ومصداقيتها وسرعة النشر',
    desc_en: 'Comprehensive evaluation of scientific journals regarding impact factor, credibility, and publication speed',
    long_desc_ar: 'تقرير تقييمي مفصّل لأي مجلة علمية تتضمن تحليل معامل التأثير، التصنيفات الدولية، سياسات النشر، نسبة القبول، وموثوقية الناشر لمساعدتك في اتخاذ قرار نشر مستنير.',
    long_desc_en: 'A detailed evaluation report for any scientific journal including impact factor analysis, international rankings, publication policies, acceptance rate, and publisher credibility to help you make an informed publication decision.',
    color_class: 'from-teal-500 to-teal-700',
    color_bg: 'bg-teal-50',
    color_text: 'text-teal-600',
    color_border: 'border-teal-200',
    roles: ['grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'تحليل معامل التأثير واتجاهه',
      'التحقق من التصنيفات (Scopus, SCI, SSCI)',
      'تقييم مصداقية الناشر',
      'إحصائيات سرعة النشر ونسبة القبول',
      'تحليل سياسات النشر والتراخيص',
      'تنبيهات حول مجلات مشبوهة',
    ],
    features_en: [
      'Impact factor analysis and trend',
      'Verification of rankings (Scopus, SCI, SSCI)',
      'Publisher credibility assessment',
      'Publication speed and acceptance rate statistics',
      'Publication policies and licenses analysis',
      'Alerts about predatory journals',
    ],
    steps_ar: [
      { title: 'إدخال اسم المجلة', desc: 'أدخل اسم أو رابط المجلة المطلوبة' },
      { title: 'التحليل', desc: 'نقوم بجمع وتحليل البيانات' },
      { title: 'التقييم', desc: 'نقيّم المجلة وفق معايير متعددة' },
      { title: 'التقرير', desc: 'استلم تقرير التقييم الشامل' },
    ],
    steps_en: [
      { title: 'Enter Journal Name', desc: 'Enter the name or link of the requested journal' },
      { title: 'Analysis', desc: 'We collect and analyze data' },
      { title: 'Evaluation', desc: 'We evaluate the journal against multiple criteria' },
      { title: 'Report', desc: 'Receive comprehensive evaluation report' },
    ],
    upload_label_ar: 'اسم المجلة أو الرابط',
    upload_label_en: 'Journal Name or Link',
    upload_accept: null,
    cta_text_ar: 'طلب تقييم مجلة',
    cta_text_en: 'Request Journal Evaluation',
  },

  'template': {
    id: 'template',
    slug: 'template',
    icon_name: 'LayoutTemplate',
    title_ar: 'قوالب البحث',
    title_en: 'Research Templates',
    desc_ar: 'قوالب جاهزة ومنسقة لأشهر المجلات العلمية لتسهيل عملية الكتابة والتنسيق',
    desc_en: 'Ready-formatted templates for top scientific journals to facilitate writing and formatting',
    long_desc_ar: 'مكتبة شاملة من القوالب الجاهزة لأكثر من 500 مجلة علمية بتنسيقاتها الرسمية، تشمل هيكل الورقة، أنماط التوثيق، تنسيق الجداول والأشكال، وصفحة العنوان.',
    long_desc_en: 'A comprehensive library of ready templates for over 500 scientific journals in their official formats, including paper structure, citation styles, table and figure formatting, and title page.',
    color_class: 'from-slate-500 to-slate-700',
    color_bg: 'bg-slate-50',
    color_text: 'text-slate-600',
    color_border: 'border-slate-200',
    roles: ['grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'أكثر من 500 قالب لمجلات مختلفة',
      'تنسيق رسمي مطابق للمجلة',
      'أنماط التوثيق مُعدّة مسبقاً',
      'هيكل الورقة جاهز بالعناوين',
      'تنسيق الجداول والأشكال',
      'تحديثات دورية للقوالب',
    ],
    features_en: [
      'Over 500 templates for different journals',
      'Official formatting matching the journal',
      'Pre-configured citation styles',
      'Paper structure ready with headings',
      'Table and figure formatting',
      'Regular template updates',
    ],
    steps_ar: [
      { title: 'البحث عن مجلة', desc: 'ابحث عن اسم المجلة المستهدفة' },
      { title: 'تحميل القالب', desc: 'حمّل القالب بصيغة Word' },
      { title: 'الكتابة', desc: 'ابدأ الكتابة مباشرة في القالب' },
      { title: 'التسليم', desc: 'أرسل البحث بتنسيقه النهائي' },
    ],
    steps_en: [
      { title: 'Search Journal', desc: 'Search for the target journal name' },
      { title: 'Download Template', desc: 'Download the template in Word format' },
      { title: 'Writing', desc: 'Start writing directly in the template' },
      { title: 'Submission', desc: 'Submit the research in its final format' },
    ],
    upload_label_ar: 'ابحث عن القالب مباشرة',
    upload_label_en: 'Search for the template directly',
    upload_accept: null,
    cta_text_ar: 'استعراض القوالب',
    cta_text_en: 'Browse Templates',
  },

  'correspondence': {
    id: 'correspondence',
    slug: 'correspondence',
    icon_name: 'Mail',
    title_ar: 'المراسلات',
    title_en: 'Correspondence',
    desc_ar: 'إعداد وصياغة المراسلات العلمية مع المجلات وردود المحكمين باحترافية',
    desc_en: 'Professional drafting of scientific correspondence with journals and responses to reviewers',
    long_desc_ar: 'نصيغ لك رسائل الغلاف، ردود المحكمين، رسائل الاستفسار، وجميع المراسلات العلمية المطلوبة بلغة أكاديمية احترافية تزيد من فرص قبول بحثك.',
    long_desc_en: 'We draft cover letters, reviewer responses, inquiry letters, and all required scientific correspondence in professional academic language that increases your research acceptance chances.',
    color_class: 'from-rose-500 to-rose-700',
    color_bg: 'bg-rose-50',
    color_text: 'text-rose-600',
    color_border: 'border-rose-200',
    roles: ['grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'صياغة رسائل الغلاف الاحترافية',
      'كتابة ردود المحكمين المنطقية',
      'رسائل الاستفسار للمجلات',
      'رسائل سحب أو نقل البحث',
      'لغة أكاديمية مقنعة',
      'تعديلات حتى الرضا',
    ],
    features_en: [
      'Professional cover letter drafting',
      'Logical reviewer response writing',
      'Journal inquiry letters',
      'Paper withdrawal or transfer letters',
      'Persuasive academic language',
      'Revisions until satisfaction',
    ],
    steps_ar: [
      { title: 'رفع المستندات', desc: 'ارفع البحث وملاحظات المحكمين' },
      { title: 'تحديد النوع', desc: 'حدد نوع المراسلة المطلوبة' },
      { title: 'الصياغة', desc: 'نقوم بصياغة المراسلة باحترافية' },
      { title: 'التسليم', desc: 'استلم المراسلة جاهزة للإرسال' },
    ],
    steps_en: [
      { title: 'Upload Documents', desc: 'Upload research and reviewer comments' },
      { title: 'Specify Type', desc: 'Specify the required correspondence type' },
      { title: 'Drafting', desc: 'We draft the correspondence professionally' },
      { title: 'Delivery', desc: 'Receive correspondence ready to send' },
    ],
    upload_label_ar: 'رفع البحث وملاحظات المحكمين',
    upload_label_en: 'Upload Research and Reviewer Comments',
    upload_accept: '.pdf,.doc,.docx',
    cta_text_ar: 'طلب صياغة مراسلات',
    cta_text_en: 'Request Correspondence Drafting',
  },

  'publication': {
    id: 'publication',
    slug: 'publication',
    icon_name: 'Send',
    title_ar: 'النشر',
    title_en: 'Publication',
    desc_ar: 'خدمة متكاملة لنشر الأبحاث في مجلات علمية محكّمة ومعترف بها دولياً',
    desc_en: 'Integrated service for publishing research in peer-reviewed internationally recognized journals',
    long_desc_ar: 'خدمة شاملة من اختيار المجلة المناسبة وحتى القبول والنشر، تشمل التحكيم، التدقيق، التنسيق، المراسلات، ومتابعة عملية النشر خطوة بخطوة مع فريق متخصص.',
    long_desc_en: 'A comprehensive service from selecting the suitable journal to acceptance and publication, including review, editing, formatting, correspondence, and step-by-step publication follow-up with a specialized team.',
    color_class: 'from-orange-500 to-orange-700',
    color_bg: 'bg-orange-50',
    color_text: 'text-orange-600',
    color_border: 'border-orange-200',
    roles: ['grad', 'phd', 'researcher', 'faculty'],
    features_ar: [
      'خدمة متكاملة من البداية للنشر',
      'اختيار المجلة الأنسب تلقائياً',
      'تحكيم + تدقيق + تنسيق شامل',
      'صياغة جميع المراسلات',
      'متابعة عملية النشر كاملة',
      'دعم حتى قبول البحث',
    ],
    features_en: [
      'Integrated service from start to publication',
      'Automatic best journal selection',
      'Review + editing + comprehensive formatting',
      'Drafting all correspondence',
      'Full publication process follow-up',
      'Support until research acceptance',
    ],
    steps_ar: [
      { title: 'رفع البحث', desc: 'ارفع البحث مع تحديد متطلباتك' },
      { title: 'التقييم الشامل', desc: 'نقيّم البحث ونختار المجلة' },
      { title: 'التحضير', desc: 'تحكيم، تدقيق، تنسيق، مراسلات' },
      { title: 'الإرسال والمتابعة', desc: 'نرسل البحث ونتابع مع المجلة' },
    ],
    steps_en: [
      { title: 'Upload Research', desc: 'Upload research specifying your requirements' },
      { title: 'Comprehensive Assessment', desc: 'We assess research and select journal' },
      { title: 'Preparation', desc: 'Review, editing, formatting, correspondence' },
      { title: 'Submission & Follow-up', desc: 'We submit research and follow up with journal' },
    ],
    upload_label_ar: 'رفع ملف البحث',
    upload_label_en: 'Upload Research File',
    upload_accept: '.pdf,.doc,.docx',
    cta_text_ar: 'طلب خدمة النشر',
    cta_text_en: 'Request Publication Service',
  },
};

// الحصول على إعدادات خدمة بالـ slug
export const getServiceConfig = (slug) => SERVICES_CONFIG[slug] || null;

// الحصول على كل الخدمات
export const getAllServices = () => Object.values(SERVICES_CONFIG);

// الحصول على خدمات دور معين
export const getServicesByRole = (role) => {
  return Object.values(SERVICES_CONFIG).filter(svc => svc.roles.includes(role));
};